"use client";

import Link from "next/link";
import { CalendarDays, Check, CheckCircle2, Clock, Download, ExternalLink, FileDown, Github, Linkedin, Mail, MapPin, MoreHorizontal, Plus, QrCode, Search, Settings, ShieldCheck, Ticket, UserCheck, Users, XCircle } from "lucide-react";
import { DashboardShell } from "./DashboardShell";
import { events } from "@/lib/data";

const people = [
  ["Ayesha Khan","ayesha@coderithm.com","The Future of Design","Approved"],
  ["Hamza Ali","hamza@gmail.com","Code & Connect 2026","Pending"],
  ["Sara Nadeem","sara@outlook.com","Founders' Breakfast","Waitlisted"],
  ["Bilal Ahmed","bilal@gmail.com","Midnight Music Fest","Rejected"],
];

export function UserSection({ section }: { section: string }) {
  const title: Record<string,string>={events:"My events",tickets:"My tickets",profile:"Profile settings",settings:"Account settings",history:"Event history"};
  return <DashboardShell role="user"><main className="dash-content"><PageTitle eyebrow="MY ACCOUNT" title={title[section]||"My account"} copy="Everything you need for your Coderithm event journey."/>
    {section==="tickets" ? <div className="ticket-list">{events.slice(0,2).map((e,i)=><article className="digital-ticket" key={e.slug}><div className={`ticket-band ${e.color}`}><Ticket/><span>{i?"PENDING":"APPROVED"}</span></div><div><span className="eyebrow">DIGITAL TICKET</span><h2>{e.title}</h2><p><CalendarDays/>{e.date}, 2026 · {e.time}</p><p><MapPin/>{e.location}</p><small>TICKET ID</small><b>CDR-2026-{1842+i}</b></div><div className="ticket-qr"><QrCode/><small>Scan at entry</small><button><Download/> Download</button></div></article>)}</div>
    : section==="profile"||section==="settings" ? <ProfileForm/>
    : <div className="portal-event-list">{events.slice(0,4).map((e,i)=><article key={e.slug}><span className={`mini-art ${e.color}`}>{e.icon}</span><div><span className="eyebrow">{i===3?"PAST EVENT":i===2?"WAITLISTED":"REGISTERED"}</span><h3>{e.title}</h3><p>{e.date} · {e.location}</p></div><span className={`status ${i===2?"pending":""}`}>{i===2?"Waitlisted":"Approved"}</span><Link href={`/events/${e.slug}`}>View <ExternalLink/></Link></article>)}</div>}
  </main></DashboardShell>
}

function ProfileForm(){return <section className="panel form-panel"><div className="profile-heading"><span className="profile-photo">FA</span><div><h2>Farha Ahmad</h2><p>Member since July 2026</p></div><button className="button">Change photo</button></div><div className="form-grid"><label>Full name<input defaultValue="Farha Ahmad"/></label><label>Email address<input defaultValue="farha@example.com"/></label><label>Phone number<input defaultValue="+92 300 0000000"/></label><label>University<input placeholder="Your university"/></label><label>Company<input placeholder="Your company"/></label><label>Job title<input placeholder="Your role"/></label><label><Linkedin/> LinkedIn profile<input placeholder="linkedin.com/in/..."/></label><label><Github/> GitHub profile<input placeholder="github.com/..."/></label><label className="wide">Portfolio URL<input placeholder="https://yourportfolio.com"/></label></div><button className="button button-coral">Save changes <Check/></button></section>}

export function OrganizerSection({section}:{section:string}){
  const title:Record<string,string>={events:"Event management",registrations:"Registrations",attendance:"Attendance & check-in",analytics:"Analytics & reports",waitlist:"Waitlist",notifications:"Notifications"};
  return <DashboardShell role="organizer"><main className="dash-content"><PageTitle eyebrow="ORGANIZER PORTAL" title={title[section]||"Organizer tools"} copy="Manage events, attendees and every detail in one place." action={section==="events"?<Link href="/organizer/events/create" className="button button-coral"><Plus/> Create event</Link>:<button className="button button-dark"><FileDown/> Export CSV</button>}/>
  {section==="events"?<EventManager/>:section==="attendance"?<Attendance/>:section==="analytics"?<Analytics/>:<RegistrationManager section={section}/>}</main></DashboardShell>
}

function EventManager(){return <div className="manage-grid">{events.slice(0,4).map((e,i)=><article className="manage-card" key={e.slug}><div className={`manage-art ${e.color}`}>{e.icon}<span className={`status ${i===3?"pending":""}`}>{i===3?"Draft":"Published"}</span></div><div><small>{e.category} · {e.date}</small><h3>{e.title}</h3><p>{e.attendees} / {e.attendees+100} registered</p><div className="capacity"><i style={{width:`${Math.min(90,e.attendees/5)}%`}}></i></div><footer><button>Edit</button><button>Registrations</button><button><MoreHorizontal/></button></footer></div></article>)}</div>}
function RegistrationManager({section}:{section:string}){return <section className="panel data-panel"><div className="table-toolbar"><label><Search/><input placeholder={`Search ${section}...`}/></label><div><button className="chip active">All <span>284</span></button><button className="chip">Pending <span>18</span></button><button className="chip">Waitlisted <span>26</span></button></div></div><table><thead><tr><th>ATTENDEE</th><th>EVENT</th><th>REGISTERED</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{people.map((p,i)=><tr key={p[0]}><td><span className="table-avatar">{p[0].split(" ").map(x=>x[0]).join("")}</span><div><b>{p[0]}</b><small>{p[1]}</small></div></td><td>{p[2]}</td><td>{i+2} Jul 2026</td><td><span className={`status ${p[3].toLowerCase()}`}>{p[3]}</span></td><td><div className="row-actions"><button title="Approve"><Check/></button><button title="Reject"><XCircle/></button><button><MoreHorizontal/></button></div></td></tr>)}</tbody></table></section>}
function Attendance(){return <><div className="checkin-stats"><div><span><Users/></span><b>284</b><small>Total approved</small></div><div><span><UserCheck/></span><b>198</b><small>Checked in</small></div><div><span><Clock/></span><b>86</b><small>Not arrived</small></div><div><span><ShieldCheck/></span><b>69.7%</b><small>Attendance rate</small></div></div><section className="scanner-panel"><div className="scanner-frame"><i></i><QrCode/><span>Camera preview</span></div><div><span className="eyebrow">LIVE CHECK-IN</span><h2>Scan attendee QR code</h2><p>Position the ticket QR inside the frame. Duplicate entries are automatically blocked.</p><button className="button button-coral"><QrCode/> Start scanner</button><div className="manual-checkin"><span>or check in manually</span><label><Search/><input placeholder="Ticket ID or attendee email"/></label></div></div></section></>}
function Analytics(){return <><div className="analytics-metrics">{[["Total registrations","1,284","+18.2%"],["Approval rate","91.4%","+3.1%"],["Attendance rate","84.8%","+5.6%"],["Waitlist conversion","42.6%","+8.2%"]].map(x=><div className="metric" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]} vs last month</small></div>)}</div><section className="panel analytics-panel"><div className="panel-head"><div><h2>Registration performance</h2><p>Daily registrations across all events</p></div><button>Last 30 days</button></div><div className="trend-bars">{[25,35,29,48,42,59,52,72,65,88,78,95,84,90].map((x,i)=><i key={i} style={{height:`${x}%`}}></i>)}</div></section></>}

export function AdminSection({section}:{section:string}){const title:Record<string,string>={users:"User management",events:"Event moderation",analytics:"Platform analytics",settings:"System configuration",organizers:"Organizer management"};return <DashboardShell role="admin"><main className="dash-content"><PageTitle eyebrow="SUPER ADMIN" title={title[section]||"Administration"} copy="Control access, content and platform-wide configuration." action={<button className="button button-dark"><Download/> Export report</button>}/>{section==="settings"?<SettingsPanel/>:<RegistrationManager section={section}/>}</main></DashboardShell>}
function SettingsPanel(){return <div className="settings-stack">{[["Registration settings","Enable automatic approval for new event registrations","Auto approval"],["Waitlist management","Automatically promote the next attendee when a place opens","Auto promotion"],["Email notifications","Send confirmations, reminders and post-event follow-ups","Email delivery"],["Security","Require email verification before ticket access","Email verification"]].map((x,i)=><section className="panel setting-row" key={x[0]}><span className="setting-icon">{i<2?<Settings/>:<Mail/>}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div><label className="toggle"><input type="checkbox" defaultChecked/><i></i></label></section>)}</div>}
function PageTitle({eyebrow,title,copy,action}:{eyebrow:string,title:string,copy:string,action?:React.ReactNode}){return <div className="dash-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</div>}
